build:
	echo "build" # TODO: Implement

pack:
	echo "Pack" # TODO: Implement

clean:
	echo "Clean" # TODO: Implement

test:
	cd .. && npm run test

doc:
	cd .. && npm run generate-docs

run:
	cd .. && npm start

profile:
	echo "Profile" # TODO: Implement

help:
	echo "Run 'npm install' and then run 'npm start'"

all:
	cd .. && npm i
